/**
 *
 * @author Owusu K <adjeibohyen@hotmail.co.uk>
 *
 *
 * @notes This is an auto generated component and preferably should not be
 * edited directly refer to readme under `dev helpers` it is generated by
 * running `yarn add-svg`
 */
import React from 'react';
import colors from '@shared/colors';

import Fallback from '@assets/svg/_fallback';

const I = {
  _fallback: Fallback,
};

export interface SvgProps {
  /**
   * Sets a custom class to root of svg component
   */
  className?: string;
  /**
   * Name of svg image
   */
  name: keyof typeof I;
  /**
   * Sets predefined button size by way of padding of the button
   */
  size?: 's' | 'm' | 'l';
  /**
   * Sets height of svg image (note add units eg 10px | 10% | 10em) defaults to 1em
   */
  width?: string;
  /**
   * Sets width of svg image (note add units eg 10px | 10% | 10em) defaults to 1em
   */
  height?: string;
  /**
   * Sets the color of svg according to the `color palette`
   * Quoted hex color values are also accepted
   * For the default gradient set this to `gradient`
   */
  color?: 'gradient' | keyof typeof colors['hex'] | string;
}

/**
 * React svg component
 */
export const Svg = ({
  className,
  name,
  size,
  width,
  height,
  color,
  ...props
}: SvgProps) => {
  const Svg = I[name] || I['_fallback'];
  const sizeValue =
    (size === 's' && '1.5em') ||
    (size === 'm' && '1.75em') ||
    (size === 'l' && '2em');

  return (
    <Svg
      className={className}
      width={width || sizeValue || '1em'}
      height={height || sizeValue || '1em'}
      color={colors.hex[color] || color}
      {...props}
    />
  );
};
