/**
 *
 * @author Owusu K <adjeibohyen@hotmail.co.uk>
 *
 *
 * @notes This is an auto generated component and preferably should not be
 * edited directly refer to readme under `dev helpers` it is generated by
 * running `yarn add-svg`
 */
import React from 'react';
import {Story, Meta} from '@storybook/react/types-6-0';

import {Svg, SvgProps} from '.';

export default {
  title: 'Components/Svg',
  component: Svg,
  parameters: {actions: {argTypesRegex: '^(before|on).*'}},
  argTypes: {},
} as Meta;

const Template: Story<SvgProps> = args => <Svg {...args} />;

export const Fallback = Template.bind({});
Fallback.args = {
  name: '_fallback',
  width: '5em',
  height: '5em',
};
