/**
 *
 * @author Owusu K <adjeibohyen@hotmail.co.uk>
 *
 *
 * @notes This is an auto generated component and preferably should not be
 * edited directly refer to readme under `dev helpers` it is generated by
 * running `yarn add-icon`
 */
import React from 'react';
import {Story, Meta} from '@storybook/react/types-6-0';

import {Icon, IconProps} from '.';

export default {
  title: 'Components/Icon',
  component: Icon,
  parameters: {actions: {argTypesRegex: '^(before|on).*'}},
  argTypes: {},
} as Meta;

const Template: Story<IconProps> = args => <Icon {...args} />;

export const Bordered = Template.bind({});
Bordered.args = {
  name: 'search_outline_regular',
  variant: 'icn1',
};

export const GreyBackground = Template.bind({});
GreyBackground.args = {
  name: 'arrow_left_outline_regular',
  variant: 'icn2',
};

export const NoBackground = Template.bind({});
NoBackground.args = {
  name: 'compass_outline_regular',
  variant: 'icn3',
};

export const BlackBackground = Template.bind({});
BlackBackground.args = {
  name: 'bin_outline_regular',
  variant: 'icn4',
  color: 'white',
};
